name: Multiple Environment Deployments

on:
  push:
    branches:
      - main

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'Building image...'

  dev-deploy:
    runs-on: ubuntu-latest
    needs: build-image
    environment: dev
    steps:
      - name: deploy
        run: echo 'Deploying to dev...'

  stg-0-deploy:
    runs-on: ubuntu-latest
    needs: [build-image, dev-deploy]
    environment: stg-0
    steps:
      - name: deploy
        run: echo 'Deploying to stg-0...'

  stg-1-deploy:
    runs-on: ubuntu-latest
    needs: [build-image, stg-0-deploy]
    environment: stg-1
    steps:
      - name: deploy
        run: echo 'Deploying to stg-1...'
        